# Generated by Django 5.0.1 on 2024-01-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('permalink', models.CharField(max_length=12, unique=True)),
                ('updatedate', models.DateTimeField(verbose_name='Last Update')),
                ('bodytext', models.TextField(blank=True, verbose_name='page content')),
            ],
        ),
    ]
